// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfG3PnGJC2-PoqrQOx7kqvlo4mXH9aUbE',
    appId: '1:1028982131067:web:dccea97e7384e40edd55de',
    messagingSenderId: '1028982131067',
    projectId: 'tachiyomi-flutter',
    authDomain: 'tachiyomi-flutter.firebaseapp.com',
    storageBucket: 'tachiyomi-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsrHVJHIIqI1BkBqfN0nQ5Cw7TuJnGJCQ',
    appId: '1:1028982131067:android:bcf614536d9582cbdd55de',
    messagingSenderId: '1028982131067',
    projectId: 'tachiyomi-flutter',
    storageBucket: 'tachiyomi-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxduCVUFXZdC88KW_dR7bFkKfzJSEGqmY',
    appId: '1:1028982131067:ios:af6e9eeeb4632952dd55de',
    messagingSenderId: '1028982131067',
    projectId: 'tachiyomi-flutter',
    storageBucket: 'tachiyomi-flutter.appspot.com',
    iosBundleId: 'com.example.tachiyomiPort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxduCVUFXZdC88KW_dR7bFkKfzJSEGqmY',
    appId: '1:1028982131067:ios:34d0e293ac5eec58dd55de',
    messagingSenderId: '1028982131067',
    projectId: 'tachiyomi-flutter',
    storageBucket: 'tachiyomi-flutter.appspot.com',
    iosBundleId: 'com.example.tachiyomiPort.RunnerTests',
  );
}
